contacts/urls.py
"""Accounts urls"""
from django.urls import path, include
from contacts import views


urlpatterns = [
    path('', views.ContactsHomeView.as_view(), name="contacts_home"),
    path('add_company', views.ContactsAddCompanyFormView.as_view(), name="add_company"),
    path('edit_company', views.ContactsEditCompanyFormView.as_view(), name="edit_company"),
    path('delete_company', views.ContactsDeleteCompanyFormView.as_view(), name="delete_company"),
    path('add_contact', views.ContactsAddContactFormView.as_view(), name="add_contact"),
    path('edit_contact', views.ContactsEditContactFormView.as_view(), name="edit_contact"),
    path('delete_contact', views.ContactsDeleteContactFormView.as_view(), name="delete_contact"),
    # path('add_mission', views.ContactsAddMissionFormView.as_view(), name="add_mission"),
    # path('delete_mission', views.ContactsDeleteMissionFormView.as_view(), name="delete_mission"),
]

myJOB/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('contacts/', include('contacts.urls'), name='contacts'),
    path('appliances/', include('appliances.urls'), name='appliances'),
    path('calendar/', include('myjob_calendar.urls'), name='myjob_calendar'),
    path('', include('dashboard.urls'), name='dashboard'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contacts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE

# Create your models here.
class Company(models.Model):
    name = models.CharField(max_length=250, default="", null=False)
    address1 = models.TextField(max_length=1024, null=False)
    address2 = models.TextField(max_length=1024, null=False)
    zipcode = models.CharField(max_length=5, null=False)
    city = models.CharField(max_length=250, null=False)
    user = models.ManyToManyField(User)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

class ContactMember(models.Model):
    first_name = models.CharField(max_length=250, null=False)
    last_name = models.CharField(max_length=250, null=False)
    company = models.ForeignKey('contacts.Company', on_delete=CASCADE)

    class Meta:
        ordering = ['company', 'last_name']

    def __str__(self):
        return self.last_name

class Mission(models.Model):
    title = models.CharField(max_length=250, null=False)
    description = models.TextField(max_length=1024, null=False)
    company = models.ForeignKey('contacts.Company', on_delete=CASCADE)
    user = models.ForeignKey(User, on_delete=CASCADE)

    class Meta:
        ordering = ['company', 'title']

    def __str__(self):
        return self.last_name

contacts/models/models.py
from django.db import models
from django.db.models.deletion import CASCADE

from accounts.models import User
from contacts.models import validator_fields


ESN = 'ESN'
SOFTWARE = 'SOFT'
ENGINEERING = 'ENG'
INDUSTRY = 'IND'
WEB = 'WEB'
COMPANY_TYPE = [
    (ESN, 'Entreprise de services numériques'),
    (SOFTWARE, 'Editeur de logiciels'),
    (ENGINEERING, 'Ingénierie'),
    (INDUSTRY, 'Industrie'),
    (WEB, 'Création de sites internet')
]

class Business(models.Model):
    name = models.CharField(max_length=250, blank=False, null=False)
    fa_icon = models.CharField(max_length=250, blank=True, null=False)

    class Meta:
        ordering = ['pk']

    def __str__(self):
        return self.name

class Company(models.Model):
    name = models.CharField(max_length=250, default="", null=False)
    type = models.CharField(choices=COMPANY_TYPE, max_length=4, blank=False, null=False)
    description = models.TextField(blank=True, null=False, default="")
    address1 = models.TextField(max_length=1024, null=False, blank=True, default="")
    address2 = models.TextField(max_length=1024, null=False, blank=True, default="")
    zipcode = validator_fields.ZipcodeField(max_length=5, null=False, blank=True, default="")
    city = models.CharField(max_length=250, null=False)
    user = models.ManyToManyField(User)
    business = models.ManyToManyField('contacts.Business')

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

class Contact(models.Model):
    first_name = models.CharField(max_length=250, null=False)
    last_name = models.CharField(max_length=250, null=False)
    company = models.ForeignKey('contacts.Company', on_delete=CASCADE)
    phone_number = validator_fields.PhoneNumberField(max_length=10, null=False, blank=True, default="")
    email = models.EmailField(max_length=254, null=False, blank=True)
    user = models.ManyToManyField(User)

    class Meta:
        ordering = ['company', 'last_name']

    def __str__(self):
        return self.last_name

    def format_phonenumber(self):

        preformatted_phone = [self.phone_number[i:i+2] for i in range(0, len(self.phone_number), 2)]

        formatted_phone = '<div class="col-10 contact-phonenumber">'
        for phone_element in preformatted_phone:
            formatted_phone += f'<span class="mr-1">{phone_element}</span>'
        formatted_phone += '</div>'


        return formatted_phone        

contacts/models/validator_fields.py
from django.db import models

from contacts.validators import validator_contacts


class ZipcodeField(models.CharField):
    default_validators = [validator_contacts.validate_zipcode]

class PhoneNumberField(models.CharField):
    default_validators = [validator_contacts.validate_phonenumber]

contacts/views.py
"""Module user.views"""
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, request
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.urls.base import reverse
from django.views.generic import TemplateView
from django.views.generic.edit import FormView

from contacts.forms import (CompanyAddForm, EditCompanyForm, CompanyDeleteForm, AddContactForm, EditContactForm, DeleteContactForm)
from contacts.models.models import Company, Contact


class ContactsHomeView(LoginRequiredMixin, TemplateView):
    """Contacts Home view"""

    template_name = "contacts/contacts.html"

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)

        companies = self.get_queryset_companies()
        context['active_page'] = 'contacts'
        context["companies"] = companies
        context["contacts"] = self.get_queryset_contacts(companies)
        # context["missions"] = self.get_queryset_missions(companies)

        return context

    def get_queryset_companies(self):
        companies = Company.objects.filter(user=self.request.user)

        return companies

    def get_queryset_contacts(self, companies):
        contacts = Contact.objects.filter(
            company__in=companies,
            user=self.request.user
        )

        return contacts

    # def get_queryset_missions(self, companies):
    #     missions = Mission.objects.filter(
    #         company__in=companies,
    #         user=self.request.user
    #     )

    #     return missions


class ContactsAddCompanyFormView(FormView):
    template_name = 'contacts/form_add_company.html'
    form_class = CompanyAddForm
    success_url = reverse_lazy('contacts_home')

    def form_valid(self, form):

        form.add_company(self.request.user)

        return super().form_valid(form)

    def form_invalid(self, form):

        error_message = self.format_error(form)

        messages.error(self.request, error_message)

        return redirect(reverse('contacts_home'))

    def format_error(self, *args):

        message = 'An error occured :\n'

        for form in args:
            error_data = form.errors.as_data()
            for error_field, error_types in error_data.items():
                message += f'  {error_field} :\n'
                for list_error_type in error_types:
                    for error_message in list_error_type:
                        message += error_message

        return message


class ContactsEditCompanyFormView(FormView):
    template_name = 'contacts/form_company.html'
    form_class = EditCompanyForm
    success_url = reverse_lazy('contacts_home')

    def form_valid(self, form):

        form.edit_company()

        return super().form_valid(form)


    def form_invalid(self, form):

        error_message = self.format_error(form)
        print(form)
        print(error_message)

        messages.error(self.request, error_message)

        return redirect(reverse('contacts_home'))

    def format_error(self, *args):

        message = str()

        for form in args:
            error_data = form.errors.as_data()
            for error_field, error_types in error_data.items():
                message += f'  {error_field} :\n'
                for list_error_type in error_types:
                    for error_message in list_error_type:
                        message += error_message

        return message

class ContactsDeleteCompanyFormView(FormView):
    template_name = 'contacts/form_delete_company.html'
    form_class = CompanyDeleteForm
    success_url = reverse_lazy('contacts_home')

    def form_valid(self, form):

        form.delete_company(self.request.user)

        return super().form_valid(form)


class ContactsAddContactFormView(FormView):
    template_name = 'contacts/form_add_contact.html'
    form_class = AddContactForm
    success_url = reverse_lazy('contacts_home')

    def form_valid(self, form):

        form.add_contact(self.request.user)

        return super().form_valid(form)


    def form_invalid(self, form):

        error_message = self.format_error(form)

        messages.error(self.request, error_message)

        return redirect(reverse('contacts_home'))

    def format_error(self, *args):

        message = str()

        for form in args:
            error_data = form.errors.as_data()
            for error_field, error_types in error_data.items():
                message += f'  {error_field} :\n'
                for list_error_type in error_types:
                    for error_message in list_error_type:
                        message += error_message

        return message

class ContactsEditContactFormView(FormView):
    template_name = 'contacts/form_contact.html'
    form_class = EditContactForm
    success_url = reverse_lazy('contacts_home')

    def form_valid(self, form):

        form.edit_contact()

        return super().form_valid(form)


    def form_invalid(self, form):

        error_message = self.format_error(form)
        print(form)
        print(error_message)

        messages.error(self.request, error_message)

        return redirect(reverse('contacts_home'))

    def format_error(self, *args):

        message = str()

        for form in args:
            error_data = form.errors.as_data()
            for error_field, error_types in error_data.items():
                message += f'  {error_field} :\n'
                for list_error_type in error_types:
                    for error_message in list_error_type:
                        message += error_message

        return message

class ContactsDeleteContactFormView(FormView):
    template_name = 'contacts/form_delete_contact.html'
    form_class = DeleteContactForm
    success_url = reverse_lazy('contacts_home')

    def form_valid(self, form):

        form.delete_contact(self.request.user)

        return super().form_valid(form)

    def form_invalid(self, form):

        print(form)


        return super().form_valid(form)

# class ContactsAddMissionFormView(FormView):
#     template_name = 'contacts/form_add_mission.html'
#     form_class = MissionAddForm
#     success_url = reverse_lazy('contacts_home')

#     def form_valid(self, form):

#         form.add_mission(self.request.user)

#         return super().form_valid(form)
    
#     def form_invalid(self, form):

#         print(form)

#         return super().form_invalid(form)


# class ContactsDeleteMissionFormView(FormView):
#     template_name = 'contacts/form_delete_mission.html'
#     form_class = MissionDeleteForm
#     success_url = reverse_lazy('contacts_home')

#     def form_valid(self, form):

#         form.delete_mission(self.request.user)

#         return super().form_valid(form)

contacts/templates/contacts/activity_icons.html
{{ business_icons_list }}

contacts/templates/contacts/add_btn.html
{% load tags_contacts %}

{% comment %} 
<!-- dropup button -->
<div class="btn-group dropup add-to-company-btn">
    <button type="button" class="btn btn-light" id="dropupMenuButtonCompany_{{company.pk}}" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fa fa-plus" aria-hidden="true"></i>
    </button>
    <div class="dropdown-menu" aria-labelledby="dropupMenuButtonCompany_{{company.pk}}">
        <!-- Dropdown menu links -->
        <button type="button" class="dropdown-item add-contact-to-company" data-toggle="modal" data-target="#modal_contact_{{company.pk}}">new contact</button>
        <button type="button" class="dropdown-item add-mission-to-company" data-toggle="modal" data-target="#modal_mission_{{company.pk}}">new mission</button>
    </div>
</div> {% endcomment %}

<!-- Modal contact_member -->
{% form_add_contact user company %}

{% comment %} <!-- Form add mission -->
{% form_add_mission user company %} {% endcomment %}

contacts/templates/contacts/card_contact.html
{% load tags_contacts %}


<div class="col-12 card card-contact overflow-auto">
    <div class="card-body">
        <div class="container">
            <div class="row align-items-center">
                <a class="col-4 contact-item"
                   href="#"
                   title="{{ contact.first_name }} {{ contact.last_name }}"
                   data-toggle="modal"
                   data-target="#modal_contact_{{contact.pk}}">

                    <div class="row contact-name justify-content-center mb-1"><i class="fas fa-user-circle fa-2x"></i></div>
                    <div class="row contact-name justify-content-center">
                        {{ contact.first_name }} {{ contact.last_name }}
                    </div>
                </a>
                <div class="col-6 contact-infos">
                    {% if contact.phone_number != '' %}
                        <div class="row align-items-center">
                            <div class="col-2"><i class="fas fa-phone-alt"></i></div>
                            <div class="col-10 contact-phonenumber">{{ contact.phone_number }}</div>
                        </div>
                    {% endif %}
                    {% if contact.email != '' %}
                        <div class="row align-items-center">
                            <div class="col-2"><i class="fas fa-envelope"></i></div>
                            <div class="col-10 contact-email">{{ contact.email }}</div>
                        </div>
                    {% endif %}
                </div>
                <div class="col-2">
                    <div>{% form_delete_contact contact.pk user %}</div>
                </div>
            </div>
        </div>
    </div>
</div>

{% form_contact contact %}

contacts/templates/contacts/company_title.html
{% load tags_contacts %}

<div class="row align-items-center card-title">
    <div class="col-2 text-center company-icon"><i class="{{company_icon}} fa-2x"></i></div>
    <div class="col-6">
        <div class="row h5 company-item">{{ company.name }} - {{ company.city }}</div>
        {% if edit_company_form %}
            <div class="row company-type">{{edit_company_form.type}}</div>
        {% else %}
            <div class="row company-type">{{company.get_type_display}}</div>
        {% endif %}
    </div>
</div>

contacts/templates/contacts/contacts.html
{% extends 'base/base.html' %}
{% load static %}
{% load tags_contacts %}

{% block title %}Contacts{% endblock  %}
{% block app_title %}My contacts{% endblock  %}

{% block meta %}
    <script src="{% static 'contacts/js/business_list.js' %}"></script>
    <script src="{% static 'contacts/js/phonenumber.js' %}"></script>
    <script src="{% static 'contacts/js/contact_hover.js' %}"></script>
    <script src="{% static 'contacts/js/edit_contact.js' %}"></script>
    <script src="{% static 'contacts/js/edit_company.js' %}"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'contacts/css/contacts.css' %}">

{% endblock  %}

{% block content %}

    <!-- List companies -->
    <!-- TODO : Convert in Bootstrap cards -->
    <div class="container-fluid">
        <div class="row">
            {% for company in companies %}
                <div class="col-lg-4 col-md-6 col-sm-12 col-contact mb-4">
                    <!-- Card Company -->
                    <div class="card card-company my-2 bg-lightblue">

                        <div class="card-company-body">
                            <a class="card-body card-company-title"
                               href="#"
                               data-toggle="modal"
                               data-target="#modal_company_{{ company.pk }}">
                                {% company_title company %}
                            </a>
                            <div class="card-body pt-0 bg-white text-dark card-company-infos">
                                <div class="container">
                                    <div class="row">
                                        <div class="col-12 mt-1 text-muted company-text">{{company.description}}</div>
                                    </div>
                                    <div class="row justify-content-center mt-3 business-list">{% activity_icons company %}</div>
                                </div>
                            </div>
                            <div class="card-body bg-white text-dark card-company-contacts">
                                <div class="container">
                                    <div class="row">
                                        {% for contact in contacts %}
                                            {% if contact.company == company %}
                                                {% card_contact contact %}
                                            {% endif %}
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                            <div class="card-body pt-0 bg-white card-company-fill"></div>
                        </div>

                        <div class="card-footer bg-white text-dark card-company-footer">
                            <div class="row justify-content-end">
                                <div class="col-6 justify-content-center btn-group" role="group" aria-label="Company button group">
                                    {% form_add_contact user company %}
                                    {% form_company company %}
                                    {% form_delete_company company user %}
                                </div>
                            </div>
                        </div>

                    </div>

                </div>
            {% endfor %}
        </div>


{% endblock  %}

contacts/templates/contacts/form_add_company.html
{% load crispy_forms_tags %}

<div class="modal fade" id="modal_company" tabindex="-1" role="dialog" aria-labelledby="modal_companyLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modal_companyLabel">Add new company</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <!-- Form add company -->
                <form method="post" action={% url 'add_company' %} id="id_form_add_company" >
                    {% csrf_token %}
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-10">
                                <div class="row">
                                    <div class="col-12">
                                        {{ company_form.name|as_crispy_field }}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-12">
                                        {{ company_form.address1|as_crispy_field }}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-12">
                                        {{ company_form.address2|as_crispy_field }}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-4">
                                        {{ company_form.zipcode|as_crispy_field }}
                                    </div>
                                    <div class="col-8">
                                        {{ company_form.city|as_crispy_field }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Add company</button>
            </div>
        </div>
    </div>
</div>

contacts/templates/contacts/form_add_contact.html
{% load crispy_forms_tags %}


<button type="button"
        class="btn btn-outline-primary add-contact-to-company"
        data-toggle="modal"
        data-target="#modal_add_contact_{{add_contact_form.company.value}}"
        title="Add contact">
    <i class="fas fa-user-plus"></i>
</button>


<div class="modal fade" id="modal_add_contact_{{add_contact_form.company.value}}" tabindex="-1" role="dialog" aria-labelledby="modal_add_contactLabel_{{add_contact_form.company.value}}" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modal_add_contactLabel_{{add_contact_form.company.value}}">Add new contact</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <!-- Form add contact -->
            <form method="post" action={% url 'add_contact' %} id="id_form_add_contact_{{add_contact_form.company.value}}" >
            {% csrf_token %}
            <div class="modal-body">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-10">
                            <div class="row">
                                <div class="col-12">
                                    {{ add_contact_form.first_name|as_crispy_field }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12">
                                    {{ add_contact_form.last_name|as_crispy_field }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12">
                                    {{ add_contact_form.phone_number|as_crispy_field }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12">
                                    {{ add_contact_form.email|as_crispy_field }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12">
                                    {{ add_contact_form.company|as_crispy_field }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Add contact</button>
            </div>
        </form>
      </div>
    </div>
</div>

contacts/templates/contacts/form_add_contact_member.html
{% load crispy_forms_tags %}

<div class="modal fade" id="modal_contact_member" tabindex="-1" role="dialog" aria-labelledby="modal_contact_memberLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="modal_contact_memberLabel">Add new contact</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <!-- Form add contact_member -->
            <form method="post" action={% url 'add_contact_member' %} id="id_form_add_contact_member" >
                {% csrf_token %}
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-10">
                            <div class="row">
                                <ul>
                                {% for error_field, error_list in contact_member_form_errors.items %}
                                    <li>{{ error_field }} : </li>
                                    <ul>
                                    {% for error in error_list %}
                                        <li>{{error.message}}</li>
                                    {% endfor %}
                                    </ul>
                                {% endfor %}
                                </ul>
                            </div>
                            <div class="row">
                                <div class="col-12">
                                    {{ contact_member_form.first_name|as_crispy_field }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12">
                                    {{ contact_member_form.last_name|as_crispy_field }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12">
                                    {{ phone_number_form.phone_number|as_crispy_field }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12">
                                    {{ email_form.email|as_crispy_field }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12">
                                    {{ contact_member_form.company|as_crispy_field }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Add contact</button>
            </div>
        </form>
      </div>
    </div>
</div>

contacts/templates/contacts/form_add_mission.html
{% load crispy_forms_tags %}

<div class="modal fade" id="modal_mission_{{add_mission_form.company.value}}" tabindex="-1" role="dialog" aria-labelledby="modal_add_missionLabel_{{add_mission_form.company.value}}" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="modal_add_missionLabel_{{add_mission_form.company.value}}">Add new mission</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <!-- Form add mission -->
            <form method="post" action={% url 'add_mission' %} id="id_form_add_mission" >
                {% csrf_token %}
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-10">
                            <div class="row">
                                <div class="col-12">
                                    {{ add_mission_form.title|as_crispy_field }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12">
                                    {{ add_mission_form.description|as_crispy_field }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12">
                                    {{ add_mission_form.company|as_crispy_field }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Add contact</button>
            </div>
        </form>
      </div>
    </div>
</div>

contacts/templates/contacts/form_delete_company.html
<form method="post" action={% url 'delete_company' %} class="class_form_delete_company" id="delete_company_form_{{delete_company_form.company_pk.value}}">
    {% csrf_token %}
    {{ delete_company_form.company_pk.as_hidden }}
</form>
<button type="submit"
        class="btn btn-danger"
        title="Delete company"
        id="delete_company_btn_{{delete_company_form.company_pk.value}}"
        form="delete_company_form_{{delete_company_form.company_pk.value}}">
    <span class="fas fa-trash"></span>
</button>

contacts/templates/contacts/form_delete_contact.html
<span>
    <form method="post" action={% url 'delete_contact' %} class="class_form_delete_contact">
        {% csrf_token %}
        {{ delete_contact_form.contact_pk.as_hidden }}
        <button type="submit" class="btn btn-outline-danger" title="Delete contact"><span class="fas fa-trash"> </span></button>
    </form>
</span>